version: '3'
services:
    foodics-app:
        container_name: foodics_app
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: 'www-data'
        volumes:
            - '.:/var/www/html'
        networks:
            - foodics-network
        depends_on:
            - foodics-db
    foodics-db:
        container_name: foodics_db
        image: mysql:8.0.31
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-foodics}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - foodics-volume:/var/lib/mysql
        ports:
            - '23306:3306'
        networks:
            - foodics-network
    foodics-mailer:
        container_name: foodics_mailer
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - foodics-network
networks:
    foodics-network:
        driver: bridge
volumes:
    foodics-volume:
        driver: local
